vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.g.have_nerd_font = true

require 'options'
require 'pack'
require 'plugins.theme'
require 'plugins.mini'
require 'plugins.treesitter'
require 'plugins.telescope'
require 'plugins.lazydev'
require 'plugins.conform'
require 'plugins.gitsigns'
require 'plugins.diffview'
require 'plugins.oil'
require 'lsp'
require 'keymaps'
require 'autocmds'
